### ISSUE TITLE
Application doesn't work on Windows 10 IoT Core 

### ISSUE THREAD

**Issue by shijiong** [djaus2/CC2650SensorTag-CS#1]
Dear David,

Thanks for your contribution. Today i test on the desktop and Window 10 IoT Core.

Desktop with 14393 is OK, though there is no barometer data . But on RPi 3 with the latest 15043, the App did not work. It seems that though i paired the CC2560 with PRi, the App still can not discover.

**Comment by djaus2** [comment]
On my RPI3 with build 14393 everything works Ok including the Barometer
![ble gatt sensortag working - 1](https://cloud.githubusercontent.com/assets/12537105/23536418/cfabbe60-0018-11e7-9897-292f1208524f.PNG)
![ble gatt sensortag working - 2 raw values](https://cloud.githubusercontent.com/assets/12537105/23536442/051a52a0-0019-11e7-9c03-002b2c4d3f0a.PNG)

.

**Comment by djaus2** [comment]
PS On my 14393 desktop it works OK.
Some times I have to start the connection, then select Unpair, then reconnect including Pairing.
Setting up latest build on RPI3

**Comment by djaus2** [comment]
Yes I think there IS a Bluetooth problem with RPI3.
May be in inherited some of the earlier desktop and phone BT issues.
"No usable Bluetooth adapter can be found".
I need to log this.
![houston we have a problem 1](https://cloud.githubusercontent.com/assets/12537105/23537103/e0dc42f4-001d-11e7-987b-daa0379f65ba.PNG)
![houston we have a problem 3](https://cloud.githubusercontent.com/assets/12537105/23537100/e06f2e26-001d-11e7-969f-68d873eb05ea.PNG)
![houston we have aproblem 2](https://cloud.githubusercontent.com/assets/12537105/23537101/e073b752-001d-11e7-820f-24775de64358.PNG)

**Comment by djaus2** [comment]
Note that my SensorTag momentarily showed in Available devices then disappeared.

**Comment by shijiong** [comment]
Yes，
I tested with RPi2, and this app works fine.
However, RPi3 can't show the paired BLE device.
Then, I remove BLE device and re-pair the device from WEBB, and this time the device shows.
And the app cost a long time to get the data and show on the screen.
Finally, It works on both RPi3 and RPi2.
Maybe, as you said, there is a Bluetooth problem with RPI3.
![img_07774](https://cloud.githubusercontent.com/assets/12369448/23538673/1092a3a2-0010-11e7-8dfc-2c6f7491fa05.jpg)

**Comment by djaus2** [comment]
Thanks for your feedback.
Bluetooth did work later. I think there is something unreliable about it.
Took a few reboots.
I suspect the OS doesn't like running with a display and having the BT setting open when they are open in Device Manager. I think there might be a collision going on.

Also there is something "flakey" where the sensor tags are listed.
SensorTags are listed in the ListBox but they can be hidden.
I will need to load up some earlier versions of the OS.
































I too have

**Comment by djaus2** [comment]
I've been drilling into this an found two issues. One a UI issue and the second a BT issue.
Second Issue: Device Pairing just doesn't happen. The confirmation doesn't show, So it doesn't await and the handler PairingRequestedHandler() doesn't get called:
 `
                   DevicePairingKinds ceremoniesSelected = DevicePairingKinds.ConfirmOnly | DevicePairingKinds.DisplayPin | DevicePairingKinds.ProvidePin | DevicePairingKinds.ConfirmPinMatch;
                    DevicePairingProtectionLevel protectionLevel = DevicePairingProtectionLevel.Default;

                    // Specify custom pairing with all ceremony types and protection level EncryptionAndAuthentication
                    DeviceInformationCustomPairing customPairing = deviceInfoDisp.DeviceInformation.Pairing.Custom;

                    customPairing.PairingRequested += PairingRequestedHandler;
                    DevicePairingResult result = await customPairing.PairAsync(ceremoniesSelected, protectionLevel);

                    customPairing.PairingRequested -= PairingRequestedHandler`

;
In the 14393 build, the app auto pairs.
On the desktop you get confirmation.
There is some XAML code for this. Will look at enacting it.

**Comment by djaus2** [comment]
First Issue.: A bitimage in the left column of the ListBox item causes the second column to be hidden.
Fix is to comment out the image:
  `      
  <DataTemplate x:Key="ResultsListViewTemplate">

            <Grid Margin="5">

                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="50"/>
                    <ColumnDefinition Width="*" MinWidth="100"/>
                </Grid.ColumnDefinitions>
                <Border Grid.Column="0" Height="40" Width="40" Margin="5" VerticalAlignment="Top">
                    
                </Border>
                <Border Grid.Column="1" Margin="5" Background`

**Comment by djaus2** [comment]
Looked into the pairing code and it doesn't work on IoT-Core, even in 14393.
I need to raise this at a higher level.

Fix is as you did, pair the SensorTag manually outside of the program.

**Comment by djaus2** [comment]
Shiijong.
Rpi3 has built in BT.
Which BT device are you using on RPI2?
Did u use that on RPI3 or the built in one?

I think the bottom line with IoT Core is that you can't programmatically BT pair unlike on the desktop. Although you can programmatically connect if paired.
